#!/bin/bash

user=`whoami`

## Check if root ##
if [ $user != root ]
then
	echo -e "	\e[1;31m! Potrzeba uprawnień roota !\e[0m"
else
	if [ $# != 1 ]
	then
		echo "Usage: $0 {1|1.3|1.6|2|normal}"
	else
		cpu0_min=`cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq`
		cpu1_min=`cat /sys/devices/system/cpu/cpu1/cpufreq/scaling_min_freq`
		cpu0_cur=`cat /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_cur_freq`
		cpu1_cur=`cat /sys/devices/system/cpu/cpu1/cpufreq/cpuinfo_cur_freq`
		
		if [ $1 != "normal" ]; then	
			## Set to given value ##	
			case $1 in
			"1") cpu_set=1000000;;
			"1.3") cpu_set=1333000;;
			"1.6") cpu_set=1667000;;
			"2") cpu_set=2000000;;
			*) echo "Usage: $0 {1|1.3|1.6|2|normal}"
			exit
			esac
		
			## Check if not already ##
			if [ $cpu0_cur == $cpu_set ] && [ $cpu1_cur == $cpu_set ]; then
				echo -e "	\e[1;34mIt's already $1 GHz\e[0m"
			else
				## CPU0 ##
				if [ $cpu0_min -gt $cpu_set ]; then
					echo $cpu_set > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
					echo $cpu_set > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
				else
					echo $cpu_set > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
					echo $cpu_set > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
				fi

				## CPU1 ##
				if [ $cpu1_min -gt $cpu_set ]; then
					echo $cpu_set > /sys/devices/system/cpu/cpu1/cpufreq/scaling_min_freq
					echo $cpu_set > /sys/devices/system/cpu/cpu1/cpufreq/scaling_max_freq
				else
					echo $cpu_set > /sys/devices/system/cpu/cpu1/cpufreq/scaling_max_freq
					echo $cpu_set > /sys/devices/system/cpu/cpu1/cpufreq/scaling_min_freq
				fi
				echo -e "	\e[1;32mCPU frequency set to $1 GHz\e[0m"
			fi
		else
			## Set to normal ##
			## Check if not already normal ##
			cpu0_max=`cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq`
			cpu1_max=`cat /sys/devices/system/cpu/cpu1/cpufreq/scaling_max_freq`
			if [ "$cpu0_min" == 1000000 ] && [ "$cpu0_max" == 2000000 ] && [ "$cpu1_min" == 1000000 ] && [ "$cpu1_max" == 2000000 ]; then
				echo -e "	\e[1;34mIt's already normal\e[0m"
			else
				## CPU0 ##
				echo 2000000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
				echo 1000000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
				## CPU1 ##
				echo 2000000 > /sys/devices/system/cpu/cpu1/cpufreq/scaling_max_freq
				echo 1000000 > /sys/devices/system/cpu/cpu1/cpufreq/scaling_min_freq
				
				echo -e "	\e[1;32mCPU frequency set to normal\e[0m"
			fi
		fi
	fi
fi
	
