#!/bin/bash

systemctl suspend
user=`whoami`
if [ "$user" == "kuba" ]; then
	slock
else
	su kuba -c slock 
fi
RUNNING=`ps --no-headers -C tint2 | wc -l`
if [ $RUNNING -gt 0 ]; then
	#sleep 1
	killall tint2
	tint2 &
fi
